#!/bin/bash
# Meilisearch restore - instructions for restoring from backup

echo "Meilisearch Restore Process"
echo "=========================="
echo ""
echo "To restore a Meilisearch backup:"
echo ""
echo "1. Copy backup to container:"
echo "   docker cp ./data/meilisearch/backup.gz thezoo-meilisearch-1:/tmp/"
echo ""
echo "2. Extract the dump:"
echo "   docker compose exec meilisearch gunzip -c /tmp/backup.gz > /meili_data/restore.dump"
echo ""
echo "3. Stop Meilisearch:"
echo "   docker compose stop meilisearch"
echo ""
echo "4. Start with import flag (temporarily modify docker-compose.yaml):"
echo "   command: [\"--import-dump\", \"/meili_data/restore.dump\"]"
echo ""
echo "5. Start Meilisearch:"
echo "   docker compose up -d meilisearch"
echo ""
echo "6. Remove the import flag from docker-compose.yaml after import completes"